eval: eval.ml
	ocamlc -o eval helpers.ml eval.ml

eval0: eval0.ml
	ocamlc -o eval0 eval0.ml

eval1: eval1.ml
	ocamlc -o eval1 eval1.ml

eval2: eval2.ml
	ocamlc -o eval2 eval2.ml

clean:
	rm -rf *.cmo *.cmi eval *.native _build
